version: '2'
services:
    ckan:
        build: ./ckan
        command: "/usr/sbin/apache2ctl -D FOREGROUND" 
        ports:
          - "8888:80"
          - "8800:8800"
        volumes:
            - ./ckan/data/ckan_storage:/ckan_storage
            - ./ckan/ckan:/ckan
    db:
      image: postgres:9.6
      environment: 
        - POSTGRES_PASSWORD=pass
        - POSTGRES_USER=ckan_default
      volumes:
          - ckandb:/var/lib/postgres/

    db_datastore:
      image: postgres:9.6
      environment: 
        - POSTGRES_PASSWORD=pass
        - POSTGRES_USER=datastore_default
      volumes:
          - ckandb_datastore:/var/lib/postgres/
    redis:
      image: redis

    solr:
      build: solr/
      ports:
       - "8983:8983"

volumes: 
  ckandb:
  ckandb_datastore:
